# File: cloudbuild.yaml
steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/reservation-api', '.' ]
  # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/reservation-api']
  # deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: ['run', 'deploy', 'reservation-api', '--image', 'gcr.io/$PROJECT_ID/reservation-api', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
logsBucket: 'gs://reservation-api-logbucket'