jwt:
  secret: 'topSecret123'
server:
  origin: https://erdem-reservation-app.herokuapp.com
db:
  url: mongodb+srv://erdem:erdem@cluster0.tfntb.mongodb.net/reservation-api?retryWrites=true&w=majority
